= MOB
Mobile Oriented Biped

== Getting started


Generate ssh key using open-ssh, this is included in ubuntu 18.04
[%hardbreaks]
Check to see if a file .ssh exists in home directory

----
cd
----

----
ls -la | grep .ssh
----

If this directory does not exist create it in your home directory

----
mkdir .ssh
----

Go into the .ssh file and generate a ssh key

----
cd .ssh
----

----
ssh-keygen
----

Now you should see two file that were generated copy the id_rsa.pub with gedit, or anyother text editor.
[%hardbreaks]
Go to your Github account, click on profile>setting>ssh>new key
[%hardbreaks]
Paste the id_rsa.pub content into profile ssh and give it a name

----
git clone https://github.com/jjanoski/MOB.git
----

----
git checkout devel
----

----
mv MOB catkin_ws
----

----
catkin_make
----

== Install Dependencies

----
sudo apt-get install pip3
----

Run command to install all project dependancies

----
pip3 install -r requirements.txt
----

== Check Mob Rviz

Type the following command to see mob the robot in rviz

*gedit URDF, within file change the .dae paths to match your computer path*

----
roslaunch mob mob_rviz.launch
----

Setup an alias(command shortcut) by opening adding command to the end of .bashrc file

----
alias mobr='roslaunch mob mob_rviz.launch'
----

----
source .bashrc
----

== Gazebo
update Gazebo to latest version

----
sudo apt-get update
----

----
curl -sSL http://get.gazebosim.org | sh
----

----
sudo apt-get upgrade
----

== MOB Inside Gazebo

Setup an alias(command shortcut) by opening adding command to the end of .bashrc file

----
alias mobg='roslaunch mob mob_gazebo.launch'
----

----
source .bashrc
----


== Creating new feature branch

----
git branch feature/<name of feature your working on>
----

----
git checkout feature/<name of feature your working on>
----

Double check that your properly checked out the branch

----
git status
----


== Commit Changes to feature branch

----
git status
----

----
git add <files listed>
----

----
git commit -m  "<type what was changed here>"
----

----
git push
----

== Merge branch to Devel

This require a peer review to be approved
[%hardbreaks]
Make sure all your commits have been pushed
[%hardbreaks]
Go to Github and create a merge request

